services:
  web-api:
    container_name: eta-regulator-board-admin-api
    environment:
      - WEB_API_PORT=5020
    build:
      context: .
      dockerfile: Dockerfile
    image: eta-regulator-board-admin-api-image
    ports:
      - "5020:5020"

    volumes:
      - deployment_data:/app/data/deployment
    depends_on:
      - database

  database:
    container_name: eta-regulator-board-admin-database
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1D#4wHm2
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data:
    driver_opts:
      type: none
      device: /home/admin-leo/eta-regulator-board-admin-database-volume
      o: bind

  deployment_data:
    driver_opts:
      type: none
      device: /home/admin-leo/eta-regulator-board-admin-deployment-volume
      o: bind

