services:
  web-api:
    container_name: energytechaudit-regulator-board-admin-toolbox-api
    environment:
      - WEB_API_PORT=5020
    build:
      context: .
      dockerfile: Dockerfile
    image: energytechaudit-regulator-board-admin-toolbox-api-image
    ports:
      - "5020:5020"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1D#4wHm2
    ports:
      - "25432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver_opts:
      type: none
      device: /home/admin-leo/_data
      o: bind

